version: "3.9"

services:
  app:
    build: .
    container_name: rag-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      PASSWORD: password
      DBNAME: rag-db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: rag-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
